In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp /content/drive/MyDrive/"Colab Notebooks"/kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download -d ashfakyeafi/spam-email-classification

Dataset URL: https://www.kaggle.com/datasets/ashfakyeafi/spam-email-classification
License(s): apache-2.0
Downloading spam-email-classification.zip to /content
  0% 0.00/207k [00:00<?, ?B/s]
100% 207k/207k [00:00<00:00, 478MB/s]

In [ ]:
! unzip spam-email-classification.zip

Archive:  spam-email-classification.zip
  inflating: email.csv

In [ ]:
import pandas as pd
import numpy as np
import os
from collections import defaultdict

In [ ]:
df = pd.read_csv('email.csv')

In [ ]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5573 entries, 0 to 5572
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5573 non-null   object
 1   Message   5573 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
df.describe()

       Category                 Message
count      5573                    5573
unique        3                    5158
top         ham  Sorry, I'll call later
freq       4825                      30

In [ ]:
df['Category'].value_counts()

Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64

In [ ]:
import string

#preprocessing the data

def preprocess_text(text):
  text = text.lower()
  text = text.translate(str.maketrans('', '', string.punctuation))
  return text

In [ ]:
df['Message'] = df['Message'].apply(preprocess_text)

In [ ]:
#tokenize

def tokenize(text):
  return text.split()

df['tokens'] = df['Message'].apply(tokenize)

In [ ]:
df.head()

,Category,Message,tokens
0,ham,go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o..."
1,ham,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,spam,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,ham,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t..."
4,ham,nah i dont think he goes to usf he lives aroun...,"[nah, i, dont, think, he, goes, to, usf, he, l..."

In [ ]:
vocab = set()

for tokens in df['tokens']:
  vocab.update(tokens)

In [ ]:
vocab

{'62220cncl',
 'asshole',
 'parked',
 'detail',
 'expecting',
 'lesson',
 'resubmit',
 '28',
 '4wrd',
 'callingforgot',
 'iam',
 'checkup',
 'panalambut',
 'wld',
 'smsd',
 'nevering',
 'fineinshah',
 'reason',
 'hopeing',
 'renting',
 'pretty',
 'attend',
 'guesses',
 'zeros',
 'dreading',
 'enna',
 'smsing',
 'dimension',
 '95pax',
 'thatmum',
 'adjustable',
 'meneed',
 'smoking',
 'pongal',
 'black',
 '2morrow',
 'regretted',
 'cartoon',
 'hostile',
 'organise',
 'isn\x92t',
 'surprise',
 'melle',
 'whn',
 '08714712388',
 'justbeen',
 'smash',
 'groovying',
 'yoga',
 'yijue',
 'crushes',
 'bro',
 'wee',
 'phil',
 'youve',
 'listening',
 'premaricakindly',
 'malarky',
 'weaknesses',
 'petrol',
 'kano',
 'kicchu',
 'callers',
 'listening2the',
 'moves',
 'spent',
 'glad',
 'forwarding',
 'dumb',
 'call2optout4qf2',
 'carry',
 'greece',
 'hen',
 '285',
 'prepared',
 'wwwidewcom',
 '81303',
 'doubles',
 'loveable',
 '£150wk',
 'ettans',
 'jason',
 'girls',
 '1childish',
 '08719899230',
 'sooo',
 'reache',
 'near',
 'coin',
 'notifications',
 'satsound\x92s',
 '£50£500',
 'jamster',
 'uh',
 'devouring',
 'fixd',
 '£10',
 'skallis',
 'gent',
 'fatty',
 'unicefs',
 'hesitate',
 'presents',
 'sitting',
 'yourinclusive',
 'atrocious',
 '420',
 'telly',
 '08715500022',
 '08715203677',
 'festival',
 'slob',
 'isvimportant',
 'itried2tell',
 'died',
 '08717509990',
 'dime',
 'yeah',
 'steering',
 'hallaq',
 'sea',
 'strongly',
 'arrange',
 'account',
 'limited',
 'teeth',
 'christ',
 'filth',
 'many',
 'positive',
 'expired',
 '09095350301',
 'ground',
 'plyr',
 'exercise',
 'dreamstake',
 'iouri',
 '08715203685',
 'w4',
 'eyeddont',
 'attention',
 'list',
 'deposit',
 'wow',
 'braved',
 'ogunrinde',
 'attracts',
 'arrested',
 'bin',
 'accessible',
 'bootydelious',
 'gre',
 'babeprobpop',
 'ku',
 '09061749602',
 'oredi',
 'runninglets',
 'cu',
 'fne',
 'promotion',
 'news',
 '5wkg',
 'footprints',
 'liverpool',
 '4u',
 'ooh',
 'illspeak',
 'tape',
 'a21',
 'gailxx',
 'voucherstext',
 '08714719523',
 'lmao',
 'heartsnot',
 'evr',
 'sometimerakheshvisitor',
 'when',
 'break',
 'boston',
 'jules',
 'thkin',
 'necessity',
 'shelf',
 'dob',
 'okvarunnathu',
 'anythiing',
 'biggest',
 'wnevr',
 'florida',
 'restwish',
 'came',
 'dependents',
 'proper',
 'scorable',
 '6',
 'remember',
 'via',
 'honeydid',
 'ji',
 'cred',
 'moviewat',
 'zed',
 '06',
 'enough',
 'calls150ppm',
 'bullshit',
 'westonzoyland',
 'fishrman',
 'hellohow',
 '74355',
 '4rowdy',
 'weather',
 'outhave',
 'dough',
 'vouchers',
 'jewelry',
 'mins',
 'bless',
 'smoke',
 'dvd',
 '6669',
 'nordstrom',
 'postcode',
 'geeee',
 'spl',
 'ammo',
 '£125',
 'helen',
 'monl8rsx',
 'getting',
 'soo',
 'mathews',
 'forgt',
 'adventuring',
 'waythis',
 '2marrow',
 'eh',
 'cried',
 'thread',
 '0844',
 'exams',
 'per',
 'stone',
 'thy',
 'telephone',
 'theyll',
 'kudiyarasu',
 'away',
 'todayhe',
 'w1t1jy',
 'mufti',
 'let',
 'move',
 'ass',
 'abbey',
 'httpcareers',
 'requests',
 'pobox202',
 '£79',
 'mondaynxt',
 'konw',
 'mel',
 'nd',
 '80608',
 '087123002209am7pm',
 '150prcvd',
 'jos',
 'eighth',
 'pass',
 'i‘ve',
 'significant',
 'something',
 'tescos',
 'module',
 'freemessage',
 'slave',
 'over',
 'harishs',
 'pure',
 'bloodsend',
 'exam',
 '02072069400',
 'walkin',
 'build',
 'goodfriend',
 'onlydon',
 'made',
 'mother',
 'lionp',
 'summers',
 'love',
 'lousy',
 'gary',
 'serious',
 'blessings',
 'postal',
 'kills',
 'randomlly',
 'oreo',
 'immediately',
 'ssnervous',
 'shahjahan',
 'wendy',
 'no440',
 'lick',
 'simulate',
 'achieve',
 'vodafone',
 '0825',
 '930',
 'occupied',
 'hmv',
 'strip',
 'sit',
 'disagreeable',
 'drinks',
 'limit',
 'meetins',
 'freesend',
 'we‘ll',
 '8714714',
 'makes',
 'booked',
 'member',
 'php',
 'sad',
 'swalpa',
 'lunch',
 'subletting',
 '£3350',
 'wake',
 '83383',
 'erutupalam',
 'nothin',
 'late',
 'deeraj',
 'katexxx',
 'legal',
 'seventeen',
 'corporation',
 'surf',
 'broth',
 'indians',
 'park',
 'transaction',
 'combination',
 'witot',
 'brilliant1thingi',
 'annoying',
 'huai',
 'rip',
 'special',
 'solihull',
 'kissing',
 'meal',
 'causes',
 'ireneere',
 'loneliness',
 'round',
 'guarantee',
 '09099726481',
 'gotmarried',
 'mostly',
 'unhappy',
 'c52',
 'healer',
 'babies',
 'ssindia',
 '6romantic',
 'lorwe',
 'qatar',
 'sara',
 '1010',
 'ü',
 'flurries',
 'bcozi',
 'uk',
 'vegetables',
 'printer',
 'apes',
 'sumfing',
 'speling',
 'txt',
 'embarassing',
 'source',
 'clock',
 'ls1',
 'coins',
 '08704439680',
 'txtno',
 'hopeafternoon',
 'uxxxx',
 'accent',
 'o2fwd',
 'wwwsmsacunatalie2k9',
 '08715203028',
 '116',
 'lying',
 'webadres',
 'rather',
 '09096102316',
 'probs',
 'everyday',
 'persevered',
 'okey',
 'text',
 'fulfil',
 'bthere',
 'claypot',
 'wall',
 'kath',
 'prior',
 'desparate',
 'enc',
 'availablethey',
 'aww',
 'kay',
 'hdd',
 'aeroplane',
 'al',
 'hate',
 'specialisation',
 'requirements',
 'kidding',
 'poker',
 'hoo',
 'hl',
 'pushbutton',
 'girld',
 'expression',
 'wth',
 'kick',
 'gt',
 'grumpy',
 '24',
 'doubt',
 '0870737910216yrs',
 'canary',
 'franxx',
 'wwwrtfsphostingcom',
 'wings',
 'music',
 'entey',
 'sw73ss',
 'usno',
 'gets',
 'cleaning',
 'predict',
 'chik',
 'freeringtone',
 'somtimes',
 'adding',
 'drugs',
 'timeslil',
 'shitjustfound',
 'platt',
 'poet',
 'drastic',
 'massages',
 '08719181503',
 '9996',
 'hands',
 'hoped',
 'wa14',
 'stdtxtrate',
 'valentine',
 'inspection',
 'melody',
 'disappointment',
 'raviyog',
 'needing',
 'immunisation',
 'avenge',
 'board',
 'murderer',
 'truffles',
 'numberpls',
 'idk',
 'problemfree',
 'transport',
 'ima',
 'replacing',
 'noise',
 '100603',
 'pobox',
 'carlie',
 'updat',
 'yesterday',
 'renewing',
 '9yt',
 'cherish',
 '11414',
 'sum1',
 'getsleep',
 'wwwringtonescouk',
 'eachother',
 'airtel',
 'newscaster',
 'msg',
 'any',
 'keralacircle',
 'uv',
 'ltdhelpdesk',
 'audrey',
 'hitechnical',
 '6230',
 'jerk',
 'prospects',
 'masters',
 'havnt',
 'calls£1minmoremobsemspobox45po139wa',
 'bye',
 'sacrifice',
 'onit',
 'can‘t',
 'quarter',
 '08718725756',
 '725',
 'messaged',
 '1205',
 'oral',
 'ability',
 'dialogue',
 '£800',
 'emailed',
 'used',
 'kate',
 'visit',
 'shut',
 '211104',
 'medont',
 'jb',
 'mumtazs',
 'dormitory',
 'nails',
 'affectionsamp',
 'detroit',
 'rays',
 'band',
 'chess',
 'style',
 'staffsciencenusedusgphyhcmkteachingpc1323',
 'husband',
 'jokin',
 'jealous',
 'iwana',
 'honi',
 'ubi',
 'desires',
 '30th',
 'honeymoon',
 'camcorder',
 'cheesy',
 'toilet',
 'implications',
 'answer',
 'went',
 '07753741225',
 'yeovil',
 '5th',
 'yun',
 'michael',
 'enjoying',
 '1680',
 'caught',
 'divert',
 'completed',
 'gr8',
 'however',
 'relax',
 'developer',
 'miserable',
 'none',
 '1013',
 'showing',
 'rodds1',
 'movie',
 'box245c2150pm',
 'breather',
 'boutxx',
 'workage',
 '01223585334',
 '4get',
 'euro2004',
 'himthen',
 '09094100151',
 'haughaighgtujhyguj',
 'prasanth',
 'lov',
 'ques',
 '08719899217',
 'kotees',
 'prescribed',
 'voice',
 'requires',
 'miss',
 'backdoor',
 'good',
 'inconsiderate',
 'waheeda',
 'varaya',
 '2c',
 'abeg',
 '9decent',
 'pobox334',
 'carewhoever',
 'abta',
 '54',
 'shoul',
 'st',
 'dealer',
 'nuther',
 'bookshelf',
 'mis',
 'ninish',
 'brothers',
 'perfume',
 'havin',
 'address',
 'bathing',
 'crazy',
 'bringing',
 'lingerie',
 'callcost',
 'to',
 '7250',
 '391784',
 'bognor',
 'compofstuff',
 'degree',
 'nitro',
 'greeting',
 'creep',
 'favor',
 '2kbsubject',
 'urgh',
 'officer',
 'homecheck',
 '08709222922',
 'trust',
 'exact',
 'georges',
 'rayan',
 'lac',
 'bong',
 'vasai',
 '84484',
 'kodthini',
 'pataistha',
 'kusruthi',
 'teresa',
 'hcl',
 'pray',
 'nora',
 'fones',
 'stated',
 'thts',
 'l8er',
 'mails',
 'lolnice',
 'puttin',
 'wicklow',
 'marvel',
 'afraid',
 'post',
 'texts',
 'dearer',
 'cum',
 'cometil',
 'ta',
 'pocy',
 'flew',
 'hyde',
 'paid',
 'friendshipmotherfatherteacherschildrens',
 'dehydrated',
 'advisors',
 'pulling',
 'swoop',
 'discuss',
 'towncud',
 'shhhhh',
 'resort',
 'true',
 'howda',
 '…thanks',
 'mall',
 'mb',
 'mumbai',
 'church',
 'stevelike',
 'likeyour',
 'free2day',
 'httpwwwgr8prizescom',
 'membership',
 'genus',
 'sn',
 'envy',
 'shortcode',
 'galno',
 'beauties',
 'tranquility',
 'inmind',
 'sentdate',
 'testing',
 'curtsey',
 'mundhe',
 '0125698789',
 'bw',
 'convince',
 'further',
 'took',
 'netno',
 'knocking',
 'charles',
 'winds',
 '6cruel',
 'trywales',
 'hospitals',
 'notebook',
 'spoiled',
 'bblue',
 'hurt',
 'found',
 '146tf150p',
 'lists',
 'wallet',
 'means',
 'entertaining',
 'fuckinniceselfishdeviousbitchanywayi\x92l',
 'bored',
 'folks',
 'kiosk',
 'another',
 'i’m',
 'earlierwe',
 '9t',
 'exp',
 'net',
 'erything',
 'wk',
 'dl',
 'poorly',
 '09065171142stopsms08',
 'monkey',
 'gudnyt',
 'won',
 'above',
 'impressively',
 'don‘t',
 'recognises',
 'cruise',
 'hai',
 'dice',
 'expiredso',
 'issue',
 'outl8rjust',
 'praises',
 'effects',
 'hair',
 '7mahaveer',
 'stewartsize',
 'fish',
 'cheer',
 'armand',
 'ltdecimalgt',
 'latests',
 'raining',
 'voted',
 'suffer',
 'province',
 'ahsen',
 'univ',
 'grandfather',
 'coveragd',
 'dd',
 'reference',
 'supervisor',
 'snuggles',
 'child',
 'voicemail',
 'topicsorry',
 '2naughty',
 'spontaneously',
 'downs',
 'rebooting',
 'alone',
 'internetservice',
 '31pmsg150p',
 'tm',
 'randy',
 'wan',
 'monday',
 'diff',
 'stop',
 'graphics',
 'packalso',
 'mids',
 '087147123779am7pm',
 'stereophonics',
 'tensed',
 'kkwhat',
 'itor',
 'evaluation',
 'age16150ppermesssubscription',
 'tortilla',
 'spelling',
 'itboth',
 'closer',
 'spain',
 'asthere',
 'common',
 'prizes',
 '69888nyt',
 'proverb',
 'members',
 'aids',
 'molestedsomeone',
 'computational',
 'suply',
 '08450542832',
 'thus',
 'lessons',
 '80122300pwk',
 'ditto',
 'beggar',
 'yday',
 'stocked',
 'bottom',
 'professors',
 'oreos',
 'vai',
 'between',
 'luck',
 'ignorant',
 'howdy',
 'gek1510',
 'mail',
 'write',
 'gua',
 'lord',
 '08000938767',
 'hut',
 'groundamla',
 'quite',
 'chop',
 'r836',
 '730pm',
 'grave',
 'emerging',
 '945',
 'mine',
 'nri',
 'wad',
 'loverboy',
 'claire',
 'html',
 'leaving',
 'hall',
 'rest',
 'various',
 'poo',
 'tag',
 'videopic',
 'colour',
 'holding',
 'arises',
 'ring',
 'able',
 'necessarily',
 'humanities',
 'inforingtonekingcouk',
 'wwwtxt43com',
 '09064012103',
 'resubbing',
 'surfing',
 'beautifulmay',
 'upnot',
 'cash',
 'phne',
 'olympics',
 'gravity',
 'executive',
 'subscribers',
 'lowes',
 'started',
 '89105',
 'kip',
 'freeringtonereply',
 'potter',
 '4years',
 'spotty',
 'leastwhich',
 'iwasmarinethat\x92s',
 '08718730555',
 'reset',
 'profile',
 'tocallshall',
 'ilol',
 'girl',
 'way',
 'anyhow',
 'meatballs',
 'remains',
 'eat',
 'subscribe',
 'shola',
 'cheque',
 'thisdon',
 'pictures',
 'either',
 'wheat',
 'short',
 'mobiles',
 'dload',
 'wrote',
 'la1',
 'wwworangecoukow',
 'madstini',
 'overtime',
 'be',
 'hasnt',
 '08712402578',
 'kkany',
 'boat',
 'grr',
 'cards',
 'smsshsexnetun',
 'touch',
 'avoids',
 'yummy',
 'doggy',
 'safety',
 'leonas',
 'wmlid1b6a5ecef91ff937819firsttrue180430jul05',
 'shudvetold',
 'timings',
 'east',
 'alle',
 'ganesh',
 'noncomittal',
 '140',
 'shouting',
 'realized',
 'hunks',
 'we',
 'lotsof',
 'takin',
 'greatest',
 '10th',
 'airport',
 'amx',
 'm26',
 'vilikkamt',
 'followin',
 'research',
 'affairs',
 'nitw',
 'u4',
 'pthis',
 'themes',
 'okden',
 'everybody',
 '£75000',
 'wherever',
 '08448714184',
 'weeks',
 '61610',
 'start',
 'theregoodnight',
 'fizz',
 '89080',
 'recdthirtyeight',
 'hungover',
 'zahers',
 'housewives',
 '30',
 'denis',
 'amused',
 'fetch',
 'using',
 'sweatter',
 'whispers',
 'iti',
 'sake',
 'programs',
 'logged',
 'computer',
 'animation',
 'tul',
 'blakes',
 'credit',
 '£50award',
 'time',
 'tank',
 'anybodys',
 'sunday',
 'job',
 'safely',
 'floating',
 ...}

In [ ]:
#initialize dictionaries

word_counts = defaultdict(lambda: {'ham':0, 'spam':0})
class_counts = {'ham':0, 'spam':0}

In [ ]:
for i, row in df.iterrows():
  class_label = row['Category']
  if class_label in class_counts:
    class_counts[class_label] += 1
    for token in row['tokens']:
      word_counts[token][class_label] += 1

  else:
    print(f"Invalid class label: {class_label}")

Invalid class label: {"mode":"full"

In [ ]:
#calculate probabilities

total_sample = len(df)
prior_ham = class_counts['ham'] / total_sample
prior_spam = class_counts['spam'] / total_sample

In [ ]:
#calculate prior probabilities

total_samples = len(df)
prior_ham = class_counts['ham'] / total_samples
prior_spam = class_counts['spam'] / total_samples

In [ ]:
#calculate likelihood probabilities

likelihood_probs = {}

for word in vocab:
  likelihood_probs[word] = {
      'ham': (word_counts[word]['ham'] + 1) / (class_counts['ham'] + len(vocab)),
      'spam': (word_counts[word]['spam'] + 1) / (class_counts['spam'] + len(vocab))
  }

In [ ]:
#prediction function

def predict(Message):
  tokens = tokenize(preprocess_text(Message))
  ham_score = np.log(prior_ham) + sum(np.log(likelihood_probs.get(word, {'ham': 1})['ham']) for word in tokens)
  spam_score = np.log(prior_spam) + sum(np.log(likelihood_probs.get(word, {'spam': 1})['spam']) for word in tokens)

  print(ham_score)
  print(spam_score)

  if ham_score > spam_score:
    return 'ham'
  else:
    return 'spam'

In [ ]:
new_email = 'Congratulations, you win this car! Click now to this link.'

predicted_class = predict(new_email)
print(f'Predicted class: {predicted_class}')

-48.65842255954074
-48.428533714136194
Predicted class: spam